# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
# https://copier.readthedocs.io/en/stable/updating/#never-change-the-answers-file-manually
_commit: v2.2.3
_src_path: gh:FallingColors/hexdummy
advanced: false
description: KVHA (Kneecore's Very Hex Addon), a suspiciously Hex Addon shaped addon
    for Hex Casting.
display_name: KVHA (Kneecore's Very Hex Addon)
github_repo: reshex
github_user: emir4169
java_package: io.github.emir4169.reshex
mappings_name: Mojmap
minecraft_version_in_mod_version: true
mit_license: true
mod_version: 0.1.0
modid: reshex
